### ISSUE TITLE
When plotting an image with limits, the axis's limits change

### ISSUE THREAD

**Issue by logankilpatrick** [jkrumbiegel/MakieLayout#11]
Hey!  I have the following: 

<img width="498" alt="Screen Shot 2019-12-12 at 5 34 57 PM" src="https://user-images.githubusercontent.com/35577566/70754641-b8c23a00-1d05-11ea-996c-de02af4dbd49.png">

this comes from `image!(axes[i, j], img[rand(400:500):1:500, rand(400:500):1:500])`

I really want the axis to maintain the original values i.e. something between `rand(400:500):1:500` 400 and 500... How do I do this? When I plot lines on the image, the lines are relative to the 400-500 so when I add the lines it gets all messed up.

**Comment by logankilpatrick** [comment]
<img width="604" alt="Screen Shot 2019-12-12 at 5 20 34 PM" src="https://user-images.githubusercontent.com/35577566/70754944-8107c200-1d06-11ea-82a3-fe624340f5d0.png">
For refrence here is what it looks like when I add lines to the axis[1,1]

**Comment by jkrumbiegel** [comment]
you need to pass the extent in addition to the array to `image!`. If you think about it, from what you passed, `image!` can't know anything about the axis values you want, it just sees the width of the array. http://makie.juliaplots.org/dev/functions-overview.html#image-1 shows this syntax:
```julia
image(x, y, image)
image(image)

Plots an image on range x, y (defaults to dimensions)
```

**Comment by logankilpatrick** [comment]
Ah, yep. Silly mistake. Thanks!

**Comment by jkrumbiegel** [comment]
so together something like:

```julia
xrange = rand(400:500):500
yrange = rand(400:500):500
image!(axes[i, j], xrange, yrange, img[xrange, yrange])
```
