### ISSUE TITLE
Add link to the awesome code that created the Readme.md gif

### ISSUE THREAD

**Issue by logankilpatrick** [jkrumbiegel/MakieLayout#13]
Can you link the code in the readme that was used to create that awesome visual?

**Comment by jkrumbiegel** [comment]
that's here: https://github.com/jkrumbiegel/MakieLayout.jl/blob/master/docs/src/visualizations/vis_01_windowresize.jl but I can't guarantee that it still works, as it's already seven days old :) I'm currently rewriting stuff in the backend, so my focus is not on stable examples, yet
