### ISSUE TITLE
Can you add a Makie Slider into am axes object

### ISSUE THREAD

**Issue by logankilpatrick** [jkrumbiegel/MakieLayout#14]
Hey, do I have to use the new slider system or can I use the old makie one and add it via indexing the axis?

**Comment by jkrumbiegel** [comment]
The new one is mostly like the old one, it just plays nicely with layouts. Is there a reason you want the old one? A label is easy to make, and once I have pushed the new api it will be even easier to put these side by side.

Also I don't understand what you mean by "indexing the axis", you can still add the old slider to your scene, but the layout will not know about it and things might overlap.
