### ISSUE TITLE
non-recursive show function

### ISSUE THREAD

**Issue by rapus95** [jkrumbiegel/MakieLayout#19]
currently when coding interactively and missing a `;` after an `LAxis` object, the whole REPL is spammed with a huge bulk of code.

**Comment by jkrumbiegel** [comment]
fixed https://github.com/jkrumbiegel/MakieLayout.jl/commit/e6f9af326de0e72c87b966ec216d5bd7b93e5cd6, although tons of makie objects still suffer from the same problem because attribute dicts are huge and often contain references to scenes as well.
