### ISSUE TITLE
Syntax ideas for plotting with layouts

### ISSUE THREAD

**Issue by jkrumbiegel** [jkrumbiegel/MakieLayout#2]
# Creating a scene with a grid layout

```julia
scene = Scene(cols = 3, rows = 5, colgap = 0.05, rowgap = 0.03)
```

# Plotting into a scene that has a grid layout

```julia
scene[1:2, 2:4] = scatter!(x, y, z)
```

pros:
- easily specify grid location

cons:
- can't save plot object in a variable

```julia
scatterobj = scatter!(scene[1:2, 2:4], x, y, z)
```

pros:
- easily specify grid location
- save plot object in variable

cons:
- ?

# Manipulating the scene layout

The layout parameters should be observables that then update the scene

```julia
scene.layout.columngap[] = 0.05
```

# Nested grid layouts

Should be easy for manual use and recipes (for example a main plot with two marginal histograms).

```julia
gl = GridLayout(rows = 2, cols = 2)
scene[1:2, 2:4] = gl
scatter!(gl[1:2, 1], x, y, z)
```

**Comment by asinghvi17** [comment]
For creating a Scene with a layout, I'd suggest that we create some form of layout constructor (`GridLayout` works fine), and just let that be passed to a `layout` kwarg in the Scene constructor.  That would IMO make it more general, and be closer to what we already have in Plots, and we can probably adopt their layout macro at no extra cost. 

I have one point of confusion here - what does the sliced indexing do?

Edit: I think I see now - it's just to allow a Scene to span more than 1 "grid square", right?
