### ISSUE TITLE
Unable to resize grid?

### ISSUE THREAD

**Issue by grero** [jkrumbiegel/MakieLayout#20]
This could be a result of me wanting to live on the edge, but the automatic layout resizing triggered by indexing outside the current grid seems broken at the moment. For example, running the example [here](https://jkrumbiegel.github.io/MakieLayout.jl/dev/index.html), I get an error on the last line:

```julia
julia> # index into the 0th row, thereby adding a new row into the layout and place
       # a text object across the first four columns as a super title
       layout[0, 1:4] = LText(scene, text="MakieLayout Facets", textsize=50)
ERROR: TypeError: in setfield!, expected Array{MakieLayout.GridContent,1}, got Array{MakieLayout.GridContent{GridLayout,_A} where _A,1}
```

**Comment by jkrumbiegel** [comment]
Thanks for the heads-up, didn't catch this when changing GridContent into a parametric struct. This way some arrays were over-specified, anyway I fixed this on master.
