### ISSUE TITLE
Legend inside axis

### ISSUE THREAD

**Issue by grero** [jkrumbiegel/MakieLayout#31]
I really like how the LLegend works, basically giving one the ability to create legend entries for arbitrary plot types. I was wondering, though, if there is any way to have the legend appear inside/overlapped with the plot itself? I find that if I try to create a normal Makie text annotation, the text gets all distorted. 
This example hopefully illustrates what I mean:

```julia
using Makie, MakieLayout
scene = Scene(resolution=(300,400), camera=campixel!)
layout = GridLayout(scene, alignmode=Outside(20))
la = LAxis(scene)
layout[1,1] = la

lines!(la, [1,2,3],[1,4,9],color="red")
lines!(la, [1,2,3],[1,8,27], color="blue")
text!(la, "y=x^2", position=(4,6),textsize=1.0,color="red")
text!(la, "y=x^3", position=(4,9),textsize=1.0,color="blue")
scene
```
![legend_test](https://user-images.githubusercontent.com/1245900/74308584-8e433a80-4da3-11ea-9b74-96573ca866f2.png)

**Comment by SimonDanisch** [comment]
This is a side effect of the different way MakieLayout does the camera transformation, which doesn't interact nicely with text rendering.
You can do:
```julia
using Makie, MakieLayout
scene = Scene(resolution=(300,400), camera=campixel!)
layout = GridLayout(scene, alignmode=Outside(20))
la = LAxis(scene)
layout[1,1] = la

lines!(la, [1,2,3],[1,4,9],color="red")
lines!(la, [1,2,3],[1,8,27], color="blue")
text!(scene, "y=x^2", position=(200,70),textsize=15.0,color="red")
text!(scene, "y=x^3", position=(200,90),textsize=15.0,color="blue")

scene
```

**Comment by grero** [comment]
Thanks! I actually ended up doing something similar, i.e. expressing the text positions using pixel coordinates instead, and that works pretty well for my purposes.

**Comment by jkrumbiegel** [comment]
For a legend inside an axis, just put it in the same layout slot :)

You also need height and width = Auto(false) so the axis doesn't shrink to legend size. And the keyword margin is exactly for this case where you want a bit of distance to the axis edge.

```julia
scene, layout = layoutscene()

ax = layout[1, 1] = LAxis(scene)
ls = [lines!(ax, 1:10, (1:10) .* i, color = rand(RGBf0)) for i in 1:5]

leg = layout[1, 1] = LLegend(scene, ls, ["line $i" for i in 1:5];
    width = Auto(false), height = Auto(false), halign = :left, valign = :top,
    margin = (10, 10, 10, 10))

scene
```

result:
<img width="434" alt="grafik" src="https://user-images.githubusercontent.com/22495855/74439035-ba29f300-4e6b-11ea-90e0-970861e255bf.png">
