### ISSUE TITLE
title! and ylabel!

### ISSUE THREAD

**Issue by yakir12** [jkrumbiegel/MakieLayout#45]
Currently, `title!`doesn't exist and therefore doesn't work on `LAxis`. `yalbel!` doesn't work on `LAxis` either.

**Comment by jkrumbiegel** [comment]
You can do `ax.title = "Title"`, the same for all other attributes. I'm not sure if I like these convenience functions for simple attribute setting because if you follow that principle, you'd need one for every attribute, even for recipes. And that gets ridiculous quite fast :)

**Comment by jkrumbiegel** [comment]
I'd rather do away with the title! function entirely, because the AbstractPlotting version is quite hacky anyway with the stacked scenes.

**Comment by yakir12** [comment]
Actually, that makes sense. We shouldn't have convenience functions for *everything*. I'll therefore close this.
