### ISSUE TITLE
strange scaling with scatter + layoutscene

### ISSUE THREAD

**Issue by edljk** [jkrumbiegel/MakieLayout#48]
I obtained an unexpected scaling of points with this examples
```julia
scene, layout = layoutscene(1, 2, resolution = (800, 400))
axis = [LAxis(scene) for k = 1:2]
layout[1, 1:2] = axis
for k = 1:2
    scatter!(axis[k], rand(20), rand(20) / 10) 
end
```

![scatter](https://user-images.githubusercontent.com/14992507/78882422-52052100-7a58-11ea-8547-670a73bbf1f5.png)

**Comment by jkrumbiegel** [comment]
In the current Makie version, scatter points are scaled in data coordinates, not screen coordinates. This is why currently you need to multiply markersizes with `AbstractPlotting.px` to get what you want.

```
using AbstractPlotting: px
scatter!(ax, rand(10, 2), markersize = 10px)
```

**Comment by edljk** [comment]
Thanks a lot. I obtained now
![scatter](https://user-images.githubusercontent.com/14992507/78885325-b2965d00-7a5c-11ea-9798-93362d0c66d9.png)
What is the simplest way to round the y-labels of the first plot?

**Comment by jkrumbiegel** [comment]
That's an annoying bug in the package `Showoff.jl` that should be fixed... If you like you could do me a favor and create an issue there, linking to this :) It only seems to happen with certain floating point numbers

**Comment by jkrumbiegel** [comment]
Or maybe it's not.. I'll have to check the code generating the ticks again

**Comment by jkrumbiegel** [comment]
just tagged a new version with a fix, for some reason the values need a bit of rounding

**Comment by edljk** [comment]
Thanks a lot!

**Comment by edljk** [comment]
I tried to experiment colorbars on the same example. In my tentative, the colorbars are not displayed in the right place. What is wrong in this call? Thanks!

```julia
using AbstractPlotting: px

scene, layout = layoutscene(1, 2, resolution = (800, 400))
scenes = Array{Any, 2}(undef, 1, 2) 
axis = [LAxis(scene) for k = 1:2]
layout[1, 1:2] = axis
for k = 1:2
    scenes[k] = scatter!(axis[k], rand(20), rand(20) / 10, markersize = 10px, 
                                    color = [rand() for k = 1:20])
    LColorbar(scene, scenes[k], width = 10, height = Relative(1.))
end
```

**Comment by jkrumbiegel** [comment]
You haven't assigned them to any place in the layout. In most plotting software the command `colorbar` might immediately place it on the right side of some subplot, but in MakieLayout you need to say where you want it, because that makes unconventional placement much easier.

**Comment by jkrumbiegel** [comment]
If you want them right of your axes, then you should not place those axes in columns 1 and 2 but 1 and 3, so the colorbars can go into 2 and 4

**Comment by edljk** [comment]
Ha ok, thanks. The following code works great.
Two last points: why there is a scale from 0 to 100 on the left? What is displayed at the bottom of the colorbar?
Thanks a lot for your nice work.
![scatter](https://user-images.githubusercontent.com/14992507/79212797-637b6e00-7e48-11ea-878c-18db93c5636f.png)

```julia
scene, layout = layoutscene(1, 4, resolution = (800, 400))
scenes = Array{Any, 2}(undef, 1,4) 
axis = [LAxis(scene) for k = 1:4]
layout[1, 1:4] = axis
for k = 1:2
    scenes[k] = scatter!(axis[1 + 2 * (k - 1)], rand(20), rand(20) / 10, markersize = 10px, 
                         color = [rand() for k = 1:20])
    c = LColorbar(scene, scenes[k], width = 10, height = Relative(1.), label = " ")
    layout[1, 2 * k] = c
end
```

**Comment by edljk** [comment]
My mistake: I ploted unused axis
![scatter](https://user-images.githubusercontent.com/14992507/79216780-0c789780-7e4e-11ea-9734-e0c4f82dce2f.png)

```julia
layout[1, 1] = axis[1]
layout[1, 3] = axis[3]
```
should replace
```julia


layout[1, 1:4] = axis
```

**Comment by jkrumbiegel** [comment]
You are creating 4 LAxis objects, in your first version those were overlaid with the colorbars, in the second version they are not in the layout and therefore end up in the lower left (you can see the frames only)

**Comment by jkrumbiegel** [comment]
You should only create two in the first place :)

**Comment by edljk** [comment]
Perfect, thanks again.

**Comment by edljk** [comment]
Sorry to come back again.
I obtained strange errors with the following (stupid) code. I tried to isolate the problem without real success. Here are my observations
* sometime (1 over 10 times on my laptop) running these lines goes wrong and produces a very long error message related to `Observables`: `...ERROR: LoadError: StackOverflowError:
...`. I hope it can be reproduced..
* it seems it is related to the colorbar but I am not sure. For instance if I define `colorrange = (0., 1.)`. I do not have error anymore.
Sorry not to be able to be more precise..

```julia
Makie.GLMakie.destroy!(Makie.GLMakie.global_gl_screen())
rows = 3; cols = 3
scene, layout = layoutscene(rows, 2 * cols, resolution = (cols * 200, rows * 200))
scenes = Array{Any, 2}(undef, rows, cols) 
axis = [LAxis(scene) for k = 1:rows, l = 1:cols]
for k = 1:rows 
    for l = 1:cols
        layout[k, 1 + 2 * (l - 1)] = axis[k, l]
    end 
end

n = 10_000
p = rand(n, 2)
nt = 2 * n
t = rand(1:n, nt, 3) # stupid triangulation

for k = 1:rows 
    for l = 1:cols 
        color = rand(9)
        scenes[k, l] = mesh!(axis[k, l], p, t, colormap = "viridis",
                             colorrange = (- rand(), 1. +  rand()),
                             color = rand(size(p, 1)), shading = false)   
        c = LColorbar(scene, scenes[k, l], width = 10, height = Relative(1.), label = " ")
        layout[k, 2 * l] = c
    end
end
Makie.display(Makie.AbstractPlotting.PlotDisplay(), AbstractPlotting.current_scene())
```
