### ISSUE TITLE
Formatting images

### ISSUE THREAD

**Issue by logankilpatrick** [jkrumbiegel/MakieLayout#5]
Hey! I am wondering if you can try out an image example given that imho, it's one of the few things in Makie currently that does not work well. Check out https://github.com/JuliaPlots/Makie.jl/issues/397 for a visual of the issue. Thanks!

**Comment by jkrumbiegel** [comment]
Check this example that I just pushed: https://github.com/jkrumbiegel/MakieLayout/blob/master/test/example7_data_aspect.jl

I have added another aspect mode for the `LayoutedAxis` which is called `DataAspect`. This aspect mode keeps the axis in the same aspect as the limits that are currently set. Should do exactly what you want :)

Note that the axes have to stay within their allotted layout rectangles, so they can only get smaller than their maximum possible size to adjust their aspect. You can also set the aspect manually with `AxisAspect(aspect_ratio)`.

<img width="499" alt="grafik" src="https://user-images.githubusercontent.com/22495855/68857821-f79fa880-06e3-11ea-957d-5faccd446cac.png">

**Comment by jkrumbiegel** [comment]
Oh and because you're rotating the image plot in your example, just rotate the actual image data before you plot it

**Comment by jkrumbiegel** [comment]
and an aspect of `nothing` will fill all the available space, but will also stretch your image if it has a different aspect
