### ISSUE TITLE
hide axis function

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#51]
This is very useful to have:
```julia
function hide_axis!(ax)
    ax.bottomspinevisible = false
    ax.leftspinevisible = false
    ax.topspinevisible = false
    ax.rightspinevisible = false
    ax.xgridvisible = false
    ax.ygridvisible = false
    ax.xticksvisible = false
    ax.yticksvisible = false
    ax.xticklabelsvisible = false
    ax.yticklabelsvisible = false
end
```
if you let me know _where_ to put it in the source, I'll add a PR.

**Comment by asinghvi17** [comment]
https://github.com/jkrumbiegel/MakieLayout.jl/blob/52f2d97f97483ebf04b4b6d97a0e7780bb9da540/src/lobjects/laxis.jl#L811 would be the best place, probably.

**Comment by jkrumbiegel** [comment]
I have added something close to this in the latest tagged version. I've updated `hidexdecorations!` and `hideydecorations!` to also hide the grid, like it was requested by a couple of people. Then, there is now `hidedecorations!` which does both at once. I didn't want to tie that together with the spines though, as they seem quite separate to me. So there is one additional function, `hidespines!`, which hides all spines in the default version. You can only hide top and right spine, which is quite common, by doing `hidespines!(ax, :t, :r)` So now you only have to do:

```julia
hidespines!(ax)
hidedecorations!(ax)
```

**Comment by Datseris** [comment]
That is fine for me, but these functions should :

* have documentation strings
* actually be somewhere in the online docs.

Otherwise very difficult to find them and use them :( 

Kind of off-topic, but not even basic things like "change the ylabel of the axis" is not somewhere in the online docs in an explicit manner. It is probably in one of the several animations, but there is no explicit page "Changing axis properties", which is very important.

I'm not judging, just noting what I would expect to find in the docs.

**Comment by jkrumbiegel** [comment]
They do have docstrings, but that new version is just in the process of being registered right now.
You are right but it's simply a lot of work to document everything :) I'm trying my best, just wrote a better tutorial for the start page today

**Comment by Datseris** [comment]
No worries, as I said I am not judging, but it helps developers when users say what is missing.

**Comment by jkrumbiegel** [comment]
And changing the axis properties is the same as changing any other properties in Makie-world, that's probably why I never felt the need to write that down somewhere. If there was a good mechanism to document all these attributes right where they are defined, it would be much less work to document them that way, which is what kept me from doing it so far. If you have a suggestion for a Documenter technique I could use?

**Comment by jkrumbiegel** [comment]
I want to avoid having to duplicate all the attributes somewhere just to document them, the best would be if it was possible to give them docstrings

**Comment by jkrumbiegel** [comment]
the way they are defined right now doesn't lend itself to doing that easily https://github.com/jkrumbiegel/MakieLayout.jl/blob/master/src/defaultattributes.jl

**Comment by Datseris** [comment]
The tutorials are amazing and the docs great, keep up the good work! Any problems I have I will open different issue, this one is done for!
