### ISSUE TITLE
`spinewidth` does not affect bottom and left spines of an LAxis

### ISSUE THREAD

**Issue by asinghvi17** [jkrumbiegel/MakieLayout#53]
Consider the following axes, with `spinewidth = 0.5`:
![fhn_dyn_tmp copy](https://user-images.githubusercontent.com/32143268/79643763-1ab61300-81c2-11ea-8107-52bcec72ee8c.png)

**Comment by jkrumbiegel** [comment]
Classic "forgot to forward the attribute" bug, I can virtually guarantee that there are more of those waiting to be found :)

**Comment by jkrumbiegel** [comment]
I just cherrypicked the commit from your branch for simplicity, thanks!
