### ISSUE TITLE
[FR] Slider that displays its value

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#58]
I use slider, but I can imagine that many would want a slider that displays its value. Here is a simple code snippet I came up with:
```
slider = LSlider(scene, range = range(...))
text_prev = LText(scene, "T =", halign = :right)
text_after = LText(scene, lift(a -> string(a), slider.value), halign = :left)
```

This works very neatly for horizontal sliders, but I imagine that it is not optimal for vertical ones. But it seems an easy fix to simply make both `halign` arguments `:center` for vertical sliders.

Maybe worth including this as possibility when making a slider? I assume that if both texts are always zero, layouting won't be affected.

**Comment by jkrumbiegel** [comment]
Good idea, I started out keeping the slider as simple as possible (before LText even) but you are right that empty texts could just be hidden and not affect the result in the default case

**Comment by Datseris** [comment]
Hi there,

I will be using this much more frequently in some new applications I will start developing soon, and I realize that it maybe be worth it to do this properly instead of copy pasting these three lines all the time.

I could do a PR that contributes this. The problem is, I am not sure how... I've had a look at the source, but the implementations are a bit daunting. I am not so sure how to go about this: should I make a new type? Should I modify the existing one? If you can guide me I can go ahead and work on it.

**Comment by jkrumbiegel** [comment]
One reason why a setup like this might not always be wanted is if you do multiple of these label slider value combinations in a vertical layout which is a grid. If every group is separate, the sliders will have different lengths depending on how long their labels are. On the one hand I do agree that it's probably a common use case, on the other hand I like it if a library doesn't offer too many combinations of its primitives which the users could easily build themselves with small functions and reuse, like you showed above.

**Comment by jkrumbiegel** [comment]
That's why I split the slider from the label in the first place, because it's not a given that slider left, label right, is what you want. In MakieLayout, the slider is really just a slider at first

**Comment by Datseris** [comment]
I completely understand your reasoning. I must argue however that in my belief, the overwhelming majority of the real-world use cases of a slider would be with a label and value. I simply find it hard to imagine that someone would use a slider in a real-world case where the slider provided no information about what it controls or what value it provides. If you recall these applications I made for InteractiveChaos, ([example](https://juliadynamics.github.io/InteractiveChaos.jl/dev/od/)), it would really make no sense to have sliders without a label. Displaying the value could be argued against (although I would definitely like to see what is the value), but for the label I find it very hard to argue against it.

The same is also true if there are more than 1 sliders in the same scene.

In any case, I will continue to re-use these 3 lines I've pasted above, and make a function that always makes something like that and makes it into a `GridLayout` so I  minimize amount of copy/paste. If at any point you want to return here just let me know.

> it's not a given that slider left, label right, is what you want.

Yes that is true, but supporting just a basic horizontal case with a single ordering of label-slider-value is already good enough. What I am talking about here is something that works well out of the box without the user having to worry about spacing issues and which combinations of `wdith = Auto(bool)` and `height = Auto(bool)` to choose. If someone wants full complete control of all exact placements, well, then they just use the elements on by one, it would be the same amount of lines of code anyway in the end of the day.

**Comment by jkrumbiegel** [comment]
The last release has a `labelslider!` function for this purpose. https://jkrumbiegel.github.io/MakieLayout.jl/v0.9.8/api_reference/#MakieLayout.labelslider!-Tuple{Any,Any,Any}

**Comment by Datseris** [comment]
I just wanted to say thank you, this worked like a charm and it has even simplified my code. I now do:
```julia
function od_sliders!(scene, controllayout)
    sliders = []
    for (i, (l, vals)) in enumerate(zip(("n =", "t =", "d =", "α ="),
                         (1000:100:100000, 1000:1000:100000, 100:100:10000, 0.001:0.001:1)))

        startvalue = l[1] == 'α' ? 0.1 : l[1] == 'd' ? 1000 : vals[1]
        sll = labelslider!(scene, l, vals; sliderkw = Dict(:startvalue => startvalue))
        push!(sliders, sll.slider)
        controllayout[i, :] = sll.layout
    end
    return sliders
end
```
and in my "main" function
```
    nslider, Tslider, dslider, αslider = od_sliders!(scene, controllayout)
```
