### ISSUE TITLE
Setting ticks is missing from the docs

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#59]
At the moment there seem to be no documentation on how to set ticks of axis.

I found out there is a constructor `ManualTicks`, yet I cannot actually instantiate it.

```
ManualTicks(1,2,3)
ManualTicks([1,2,3])
```
neither work and ManualTicks also has no docstring.

**Comment by Datseris** [comment]
Of course, I find the answer after opening the issue. One needs to provide both tick locations as well as strings for each tick!!!

(Would be nice to have a convenience constructor that automatically fills the tick labels with `string.(ticks)`.

**Comment by jkrumbiegel** [comment]
My non-documentation of some of these might stem from Juno showing the signatures on autocomplete, and then it's obvious.. Of course for other users it might be different

<img width="668" alt="grafik" src="https://user-images.githubusercontent.com/22495855/80312368-29658100-87e5-11ea-9da5-27790b75f325.png">

**Comment by Datseris** [comment]
This wasn't my main target when I said "there seem to be no documentation on how to set ticks of axis".

How would a user become aware of the existence of `ManualTicks`, since it is nowhere in the documentation? It is only by luck that I have seen it, because I am a regular at the `#makie` channel on slack.

**Comment by jkrumbiegel** [comment]
https://jkrumbiegel.github.io/MakieLayout.jl/stable/laxis/#Modifying-ticks-1
