### ISSUE TITLE
What is limiting the size of my elements here? 

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#62]
I've updated to 0.7 (but not sure whether this is an issue in 0.6 as well), and I want to ask 2 things.

1. What is limiting the size of the elements I create in the below code?
2. Why are the buttons without text...?

Code:
```julia
using Makie, MakieLayout, Observables

scene, layout = layoutscene()
display(scene)

function observable_slider!(layout, i, j, scene, ltext, r; wl = nothing, wr = nothing)
    slider = LSlider(scene, range = r)
    text_prev = LText(scene, "$ltext =", halign = :right)
    text_after = LText(scene, lift(a -> "$(round(a))", slider.value),
    halign = :left)
    layout[i, j] = hbox!(text_prev, slider, text_after)
    return slider
end
function controlwindow(scene, D, i0, parname)
    controllayout = GridLayout()
    # Sliders
    nslider = observable_slider!(controllayout, 1, :, scene, "n", 1000:1000:1000000)
    Tslider = observable_slider!(controllayout, 2, :, scene, "Ttr", 1000:1000:1000000)
    dslider = observable_slider!(controllayout, 3, :, scene, "d", 100:100:10000)
    αslider = observable_slider!(controllayout, 4, :, scene, "α", 0:0.001:1)
    # Buttons (incl. variable chooser)
    ▢update = LButton(scene, label = "update")
    ▢back = LButton(scene, label = "← back")
    ▢reset = LButton(scene, label = "reset")
    imenu = LMenu(scene, options = [string(j) for j in 1:D])
    controllayout[5, :] = hbox!(▢update, ▢back, ▢reset, LText(scene, "variable:"), imenu)
    # Limit boxes. Unfortunately can't be made observables yet...
    ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊ = Observable.((0.0, 1.0, 0.0, 1.0))
    text_p₋ = LButton(scene, label = lift(o -> "$(parname)₋ = $(o)", ⬜p₋))
    text_p₊ = LButton(scene, label = lift(o -> "$(parname)₊ = $(o)", ⬜p₊))
    text_u₋ = LButton(scene, label = lift(o -> "u₋ = $(o)", ⬜u₋))
    text_u₊ = LButton(scene, label = lift(o -> "u₊ = $(o)", ⬜u₊))
    controllayout[6, :] = hbox!(text_p₋, text_p₊)
    controllayout[7, :] = hbox!(text_u₋, text_u₊)

    return controllayout, nslider.value, Tslider.value, dslider.value, αslider.value,
           imenu.selection, ▢update.clicks, ▢back.clicks, ▢reset.clicks,
           ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊
end

# ax = layout[1,1] = LAxis(scene)

controllayout, = controlwindow(scene, 5, 1, "p")

layout[:, :] = controllayout
```
output:

![image](https://user-images.githubusercontent.com/19669089/80287746-5f4a2d00-8733-11ea-8e95-ba63b8572759.png)

**Comment by jkrumbiegel** [comment]
I don't know about the text being invisible (I didn't touch button code in a while so it shouldn't be because of updating). The general logic for layouts that shrink is that the default column and rowsize for every grid layout is Auto(true). That means the layout will shrink to any object that has (and reports) a fixed size. To avoid that, either set an object's size to `Auto(false)`, or the column / row size to `Auto(false)`.

It looks like the layout is shrinking to the two buttons in the lower part?
If you make a row with `hbox!` then you can also give the resulting `GridLayout` a width of `Auto(false)` or `nothing` and it will not be inferred further.
`hbox!(stuff..., width = Auto(false))`

I am still thinking about ways to make this a bit clearer, but this is the current state.

**Comment by Datseris** [comment]
This is the version I have now after your comments and a lot of trial and error:
```julia
function controlwindow(scene, D, parname)
    controllayout = GridLayout(height = Auto(false), width = Auto(true))
    # Sliders
    nslider = observable_slider!(controllayout, 1, :, scene, "n", 1000:1000:1000000)
    Tslider = observable_slider!(controllayout, 2, :, scene, "t", 1000:1000:1000000)
    dslider = observable_slider!(controllayout, 3, :, scene, "d", 100:100:10000)
    αslider = observable_slider!(controllayout, 4, :, scene, "α", 0:0.001:1)
    # Buttons (incl. variable chooser)
    ▢update = LButton(scene, label = "update")
    ▢back = LButton(scene, label = "← back")
    ▢reset = LButton(scene, label = "reset")
    imenu = LMenu(scene, options = [string(j) for j in 1:D])
    # imenu = LText(scene, "text")
    controllayout[5, :] = hbox!(▢update, ▢back, ▢reset)
    controllayout[6, :] = hbox!(LText(scene, "variable:"), imenu)
    # Limit boxes. Unfortunately can't be made observables yet...
    ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊ = Observable.((0.0, 1.0, 0.0, 1.0))
    text_p₋ = LText(scene, lift(o -> "$(parname)₋ = $(o)", ⬜p₋), width = Relative(0.5), haligh = :left)
    text_p₊ = LText(scene, lift(o -> "$(parname)₊ = $(o)", ⬜p₊), width = Relative(0.5), haligh = :left)
    text_u₋ = LText(scene, lift(o -> "u₋ = $(o)", ⬜u₋), width = Relative(0.5), haligh = :left)
    text_u₊ = LText(scene, lift(o -> "u₊ = $(o)", ⬜u₊), width = Relative(0.5), haligh = :left)
    controllayout[7, :] = hbox!(text_p₋, text_p₊)
    controllayout[8, :] = hbox!(text_u₋, text_u₊)

    return controllayout, nslider.value, Tslider.value, dslider.value, αslider.value,
           imenu.selection, ▢update.clicks, ▢back.clicks, ▢reset.clicks,
           ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊
end

ax = layout[1,1:2] = LAxis(scene, height = Auto(true))

controllayout, = controlwindow(scene, 5, "p")

layout[1,3] = controllayout
```

which makes 

![image](https://user-images.githubusercontent.com/19669089/80289405-76424c80-873e-11ea-92e9-79eff9140658.png)


There are the following problems:

1. The left axis doesn't take 2/3 of the scene, because the control layout has fixed width. Why does it have fixed width? How do I make it so that it takes the amount of space it is supposed to?
2. I still cannot figure out why the buttons don't show any text. Its not because I use observables for them, normal text also doesn't work. Can you please generate a button on version 0.7 on your end and confirm?
3. Even though I choose `halign = :left` for the texts, e.g. `text_u₋`, they are not left-aligned. Why?

**Comment by Datseris** [comment]
Yeah, I don't really get it. As far as I can tell, I am doing exactly the same thing as the MakieLayout tutorial. Making a `GridLayout` and then giving this to `layout[:,3]`. I could use `layout[:,2] ` and it doesn't make a difference.

**Comment by jkrumbiegel** [comment]
> so that it takes the amount of space it is supposed to

Well what is the amount of space it's supposed to take? If you have only fixed width elements in a gridlayout, it usually becomes fixed width as well, because that's just sensible. I don't know just from your code what you actually want

> Even though I choose halign

You didn't write `halign` but `haligh`

I did try creating a button right now and it worked fine, my guess is that for some reason the z order can be switched, so the text is behind the button background. You can try setting that color with some alpha to check?

**Comment by jkrumbiegel** [comment]
Ah, your buttons are still fixed width and keep the layout small. Make your buttons with width Auto(false) or the hbox that they're in

**Comment by Datseris** [comment]
Thanks for the support. It is not easy for me to resolve and understand everything. At least not yet. So, here is the code:
```julia
scene, layout = layoutscene()
display(scene)

function observable_slider!(layout, i, j, scene, ltext, r; wl = 40, wr = nothing)
    slider = LSlider(scene, range = r)
    text_prev = LText(scene, "$ltext =", halign = :right)
    text_after = LText(scene, lift(a -> "$(string(a))", slider.value),
    halign = :left)
    layout[i, j] = hbox!(text_prev, slider, text_after, width = Auto(false))
    return slider
end
function controlwindow(scene, D, parname)
    controllayout = GridLayout(height = Auto(false), width = Auto(true))
    # Sliders
    nslider = observable_slider!(controllayout, 1, :, scene, "n", 1000:1000:1000000)
    Tslider = observable_slider!(controllayout, 2, :, scene, "t", 1000:1000:1000000)
    dslider = observable_slider!(controllayout, 3, :, scene, "d", 100:100:10000)
    αslider = observable_slider!(controllayout, 4, :, scene, "α", 0:0.001:1)
    # Buttons (incl. variable chooser)
    ▢update = LButton(scene, label = "update", buttoncolor = RGBAf0(0.9, 0.9, 0.9, 0.5))
    ▢back = LButton(scene, label = "← back")
    ▢reset = LButton(scene, label = "reset")
    controllayout[5, :] = hbox!(▢update, ▢back, ▢reset, width = Auto(false))
    imenu = LMenu(scene, options = [string(j) for j in 1:D], width = 60)
    imenu.selection[] = "1"
    controllayout[6, :] = hbox!(LText(scene, "variable:"), imenu, width = Auto(false))
    # Limit boxes. Unfortunately can't be made observables yet...
    ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊ = Observable.((0.0, 1.0, 0.0, 1.0))
    text_p₋ = LText(scene, lift(o -> "$(parname)₋ = $(o)", ⬜p₋), halign = :left)
    text_p₊ = LText(scene, lift(o -> "$(parname)₊ = $(o)", ⬜p₊),  halign = :left)
    text_u₋ = LText(scene, lift(o -> "u₋ = $(o)", ⬜u₋), halign = :left)
    text_u₊ = LText(scene, lift(o -> "u₊ = $(o)", ⬜u₊), halign = :left)
    controllayout[7, :] = hbox!(text_p₋, text_p₊, width = Auto(false))
    controllayout[8, :] = hbox!(text_u₋, text_u₊, width = Auto(false))

    return controllayout
    # return nslider.value, Tslider.value, dslider.value, αslider.value,
    #        imenu.selection, ▢update.clicks, ▢back.clicks, ▢reset.clicks,
    #        ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊
end

ax = layout[:,1:3] = LAxis(scene, height = Auto(true))
controllayout = controlwindow(scene, 5, "p")
layout[:,4:5] = controllayout
```


![image](https://user-images.githubusercontent.com/19669089/80291168-8b71a800-874b-11ea-9ec7-9853e1fc8a0a.png)


It does everything almost perfectly. But there are still 3 difficulties:

1. You are correct. For some reason the text appears behind the box. Adding alpha reveals some of the text. Why does this happen?
2. Thank you for pointing out the typo, my brain is fried I spent way too much time today developing interactive applications. But even though I chose `halign = :left` , the text is still in the center. I would like to have it equispaced, filling "two imaginary columns" from the actual column available to the control panel. I've tried to sketch on the figure what I want.
3. How do I set a default choice for LMenu? The text it has is overly large, and my choices are just integer numbers. I'd like to set it to have choice `1` or so. I've tried setting a value for the observable directly, but that also didn't work.

**Comment by jkrumbiegel** [comment]
Here's an example:

```julia
scene, layout = layoutscene()

ax = layout[1, 1] = LAxis(scene)
subgl = layout[1, 2] = GridLayout(height = Auto(false))

colsize!(layout, 1, Relative(2/3))

for i in 1:4
    subgl[i, 1] = hbox!(
        LText(scene, "var ="),
        LSlider(scene),
        LText(scene, "12345")
    )
end

subgl[5, 1] = hbox!([LButton(scene, label = "Button $i") for i in 1:3]..., width = Auto(false))
subgl[6, 1] = hbox!(LText(scene, "variable:"), LMenu(scene))
subgl[7, 1] = grid!([LText(scene, "p = 0.0", halign = :left, width = Auto(false)) for i in 1:2, j in 1:2])

scene
```

<img width="724" alt="grafik" src="https://user-images.githubusercontent.com/22495855/80300375-77a26200-879c-11ea-8f7c-455551df4457.png">


> Why does this happen?

I think I never set the z value of button frame and text explicitly, so far the implementation relied on text always being drawn after meshes by GLMakie, but maybe this is not always true and I should displace the text a bit. But as you can see in my screen shot, for me it works..

**Comment by jkrumbiegel** [comment]
Ah yeah I didn't really implement pre-choosing a value in the selector, you can set `menu.i_selected = 1` for now after creating it, that's the relevant variable which then also changes `menu.selection`

**Comment by Datseris** [comment]
Thank you very much for the support. Everything works now, as far as layouting goes. for clarity, here is the full code:
```julia
function observable_slider!(layout, i, j, scene, ltext, r; wl = 40, wr = nothing)
    slider = LSlider(scene, range = r)
    text_prev = LText(scene, "$ltext =", halign = :right)
    text_after = LText(scene, lift(a -> "$(string(a))", slider.value),
    halign = :left)
    layout[i, j] = hbox!(text_prev, slider, text_after)
    return slider
end
function controlwindow!(controllayout, scene, D, parname)
    # Sliders
    nslider = observable_slider!(controllayout, 1, :, scene, "n", 1000:1000:1000000)
    Tslider = observable_slider!(controllayout, 2, :, scene, "t", 1000:1000:1000000)
    dslider = observable_slider!(controllayout, 3, :, scene, "d", 100:100:10000)
    αslider = observable_slider!(controllayout, 4, :, scene, "α", 0:0.01:1)
    # Buttons (incl. variable chooser)
    ▢update = LButton(scene, label = "update")
    ▢back = LButton(scene, label = "← back")
    ▢reset = LButton(scene, label = "reset")
    imenu = LMenu(scene, options = [string(j) for j in 1:D], width = 60)
    imenu.i_selected = 1
    controllayout[5, 1] = hbox!(
        ▢update, ▢back, ▢reset,
        LText(scene, "variable:"), imenu, width = Auto(false)
    )
    # Limit boxes. Unfortunately can't be made observables yet...
    ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊ = Observable.((0.0, 1.0, 0.0, 1.0))
    tsize = 16
    text_p₋ = LText(scene, lift(o -> "$(parname)₋ = $(o)", ⬜p₋),
        halign = :left, width = Auto(false), textsize = tsize)
    text_p₊ = LText(scene, lift(o -> "$(parname)₊ = $(o)", ⬜p₊),
        halign = :left, width = Auto(false), textsize = tsize)
    text_u₋ = LText(scene, lift(o -> "u₋ = $(o)", ⬜u₋),
        halign = :left, width = Auto(false), textsize = tsize)
    text_u₊ = LText(scene, lift(o -> "u₊ = $(o)", ⬜u₊),
        halign = :left, width = Auto(false), textsize = tsize)
    controllayout[6, 1] = grid!([text_p₋ text_p₊ ; text_u₋ text_u₊])
    ⬜p₋[], ⬜p₊[], ⬜u₋[], ⬜u₊[] = rand(4)
    return nslider.value, Tslider.value, dslider.value, αslider.value,
           imenu.i_selected, ▢update.clicks, ▢back.clicks, ▢reset.clicks,
           ⬜p₋, ⬜p₊, ⬜u₋, ⬜u₊
end

scene, layout = layoutscene()
display(scene)
ax = layout[1,1] = LAxis(scene)
controllayout = layout[1, 2] = GridLayout(height = Auto(false))
colsize!(layout, 1, Relative(3/5))
display(scene)
controlwindow!(controllayout, scene, 5, "p")
```

![image](https://user-images.githubusercontent.com/19669089/80303357-2d2ae080-87b0-11ea-80e4-9191d29c5d92.png)

The only remaining issue is that as you can see text is still behind the buttons. Oddly enough, when I run your own example, I get normal buttons with text in front. So there is something weird happening at some point in my code. But I can't figure out what...

**Comment by jkrumbiegel** [comment]
I just tagged 0.7.1 with a possible fix, should be up in a bit.
