### ISSUE TITLE
Slider observables should infer type

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#64]
Making a slider with something as simple as:
```
slider = LSlider(scene, range = 0:0.1:1)
```
makes an `Observable{Any}` , which makes bugs harder to hide, because you don't get errors when updating the slider's value. It should be easy to just use the `eltype(range)` as the parameter of the observable?

**Comment by jkrumbiegel** [comment]
Observable attributes are always typed `Any` in Makie because otherwise you can't change their values to anything else after creation (like `:red` or `RGB`, etc.). A slider's value typing is also not performance critical. So it's probably not going to change.
