### ISSUE TITLE
button text is pixelated now

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#66]
In the new version the button text is now pixelated with white pixels around it like heavy aliasing.

![image](https://user-images.githubusercontent.com/19669089/80307609-640df000-87ca-11ea-9566-364776397ecc.png)

This is not the case for e.g. the LMenu button 

![image](https://user-images.githubusercontent.com/19669089/80307612-6c662b00-87ca-11ea-8599-5a01d925a952.png)

**Comment by jkrumbiegel** [comment]
oh damn that's because the text is created before the background, I'll have to fix this too

**Comment by Datseris** [comment]
I'm sorry to put so much work on you :D But you'll get full acknowledgement once I announce InteractiveChaos.jl :D

**Comment by jkrumbiegel** [comment]
should be fixed in the last tagged version, hopefully (once it merges)
