### ISSUE TITLE
[Doc] How to "auto-readjust" axis limits for interactive plotting?

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#67]
Hi, I am doing something simple like:
```julia
tsax = layout[end+1, :] = LAxis(scene)
tsobs = Observable(zeros(size(A, Time)))
lines!(tsax, 1:size(A, Time), tsobs)

on(spoint) do  pos
    i = findnearest(pos[1], lon)
    j = findnearest(pos[2], lat)
    tsobs[] = Array(A)[i, j, :]
end

```

I.e. I am plotting a line on an axis and then interactively I change the line to something else. But, unfortunately, this doesn't readjust the y-axis. I guess that there is a command to do this, but I couldn't find it in the docs.

**Comment by Datseris** [comment]
To clarify: I can of course set the `ylimits` in the `on` code block, but I am searching for the "nice autolimiter" function that also adds a little pad between data and splines, something like `readjust_limits!(ax)`.

**Comment by jkrumbiegel** [comment]
`autolimits!(ax)`, although now I'm wondering if I made a specific one just for x or y?

**Comment by Datseris** [comment]
Thanks this is what I wa s looking for
