### ISSUE TITLE
assigning to grid doesn't replace previous axis

### ISSUE THREAD

**Issue by ssfrr** [jkrumbiegel/MakieLayout#7]
Given the assignment syntax used to place a `LayoutedAxis` in a `GridLayout` I expected that I could replace it as below, but it seems that both axes are present afterwards. Obviously I wouldn't have this code as-is, but it comes up when working iteratively at the REPL.

```julia
scene = Scene(resolution = (1200, 900), camera=campixel!)

layout = GridLayout(2,2, parent=scene, alignmode=Outside(20))
layout[1,1] = LayoutedAxis(scene)
layout[1,1] = LayoutedAxis(scene, titlevisible=false, ylabelvisible=false)
```

**Comment by jkrumbiegel** [comment]
I see that this can be confusing, but it's more of a "feature". The grid layout is not like a matrix where you assign plots to slots. The assignment syntax instead creates a `SpannedAlignable` which is a layout object combined with two ranges, one for rows and one for columns. It might be desirable to place multiple layout objects in the same cells or partly covering the same cells in some scenarios. For example I would solve a plot with two different y axes this way.

**Comment by asinghvi17** [comment]
Perhaps we could abuse Observables-like syntax here, with `layout[1,1][]` updating, and `layout[1, 1]` replacing?
