### ISSUE TITLE
Spurious repeated mouse event

### ISSUE THREAD

**Issue by ericphanson** [jkrumbiegel/MakieLayout#73]
(Or maybe a plotting issue?)

The following is a simple adaptation from https://gist.github.com/jkrumbiegel/7be90a08be76f44233bc2a206dc86fbd

The issue is that `onmouseleftdragstop` can get fired multiple times per `onmouseleftdragstart` event. This seems to only happen when the `onmouseleftdragstop` event triggers some more plotting (but not, e.g., if you do `svd(rand(500,500))` or `sleep(2)` instead, so it doesn't seem like it's necessarily an async issue). If you run the following code and do some rectangle-selecting, you should soon see some `Impossible!` messages in the log. Thanks to @SimonDanisch for helping me reduce the MWE. (My workaround is to use the `dragging` bool and early return if we're in an impossible state, and that works fine but it seems like there's an underlying issue somewhere.)

```julia
using Makie, MakieLayout

##
scene, layout = layoutscene()

ax = layout[1, 1] = LAxis(scene)
layout[2,1] = bottom_ax = LAxis(scene)

heatmap!(ax, randn(500, 500))
tightlimits!(ax)

start_pos = Ref(Point2f0(0, 0))
current_pos = Ref(Point2f0(0, 0))
rectnode = Node(BBox(0, 10, 0, 10))
rectplot = Ref{Union{Nothing, Poly}}(poly!(ax, rectnode, color = (:blue, 0.05), strokecolor = (:blue, 0.5),
    strokewidth = 2,xautolimits = false, yautolimits = false, visible = false))

dragging = Ref(false)

scenestate = MakieLayout.addmousestate!(ax.scene)

MakieLayout.onmouseleftdragstart(scenestate) do state
    @info "onmouseleftdragstart triggered"
    dragging[] = true
    start_pos[] = state.pos
end

MakieLayout.onmouseleftdrag(scenestate) do state
    current_pos[] = state.pos
    c = current_pos[]
    s = start_pos[]

    rectnode[] = let
        minx, miny = min.(s, c)
        maxx, maxy = max.(s, c)
        
        BBox(minx, maxx, miny, maxy)
    end
    rectplot[].visible = true
end

MakieLayout.onmouseleftdragstop(scenestate) do state
    @info "onmouseleftdragstop triggered"
    if !dragging[]
        @info "Impossible!"
        return
    else
        dragging[] = false
    end
    rectplot[].visible = false
    ax.limits[] = rectnode[]
    lines!(bottom_ax, rand(100)) # key to trigger the issue
end

scene

```

**Comment by jkrumbiegel** [comment]
Uhh that seems weird.. I can reproduce on my Macbook. I don't think it's a bug in the mouse state machine, rather the weirdness must stem from GLFW or GLMakie's handling of GLFW's events. @SimonDanisch what do you think, could this be caused by the asynchronicity of the event loop which causes two drags? Adding to that, I often felt that mouse actions are a bit non-deterministic. Sometimes I click and nothing happens, and this double drag issue would point to the opposite problem.
