### ISSUE TITLE
right yaxisposition looks funky

### ISSUE THREAD

**Issue by yakir12** [jkrumbiegel/MakieLayout#74]
When `yaxisposition = :right` then the horizontal alignment of `yticklabelalign` should automatically be set to `:left`. Right now:
```julia
scene, layout = layoutscene()
ax = layout[1,1] = LAxis(scene, yaxisposition = :right)
scatter!(ax, rand(Point2f0, 5))
```
looks like this:
![a](https://user-images.githubusercontent.com/3281957/81962904-b21d5300-9614-11ea-9a6c-6459cbfff649.png)
While this:
```julia
scene, layout = layoutscene()
ax = layout[1,1] = LAxis(scene, yaxisposition = :right, yticklabelalign = (:left, :center))
scatter!(ax, rand(Point2f0, 5))
```
looks great:
![a](https://user-images.githubusercontent.com/3281957/81963265-27892380-9615-11ea-90d1-7facfcab4c97.png)

**Comment by yakir12** [comment]
And the same thing for `xaxisposition = :top, xticklabelalign = (:center, :bottom)`.

**Comment by jkrumbiegel** [comment]
yeah it could be, but for rotated labels that might not be correct, anyway I should make a convenience function for this

**Comment by jkrumbiegel** [comment]
I've included four convenience functions for this in the latest release. https://jkrumbiegel.github.io/MakieLayout.jl/v0.9.8/api_reference/#MakieLayout.xaxis_bottom!-Tuple{LAxis}
