### ISSUE TITLE
Tick labels misplaced with xaxisposition = :top

### ISSUE THREAD

**Issue by sairus7** [jkrumbiegel/MakieLayout#76]
```
using AbstractPlotting
using MakieLayout

scene, layout = layoutscene(resolution = (1200, 800))
ax1 = layout[1, 1] = LAxis(scene, xaxisposition = :top)
scene
```

![image](https://user-images.githubusercontent.com/20798349/82384189-ff942880-9a37-11ea-817f-278dd1fb9635.png)

**Comment by sairus7** [comment]
With `xaxis_top!(ax1)` it looks fine.

**Comment by jkrumbiegel** [comment]
yup that's because the ticklabel alignment is not directly tied to axis position (because of rotated labels there's not one "correct" alignment)
