### ISSUE TITLE
Performance question

### ISSUE THREAD

**Issue by philtomson** [jkrumbiegel/MakieLayout#78]
Perhaps this is a makie question in general, but as I'm using MakieLayout I thought I'd ask here first.

I've got the following code:
```
using Makie
using MakieLayout
using AbstractPlotting

outer_padding = 30
scene, layout = layoutscene(outer_padding, resolution = (600, 600),
                backgroundcolor = RGBf0(0.98, 0.98, 0.98))
axes = [LAxis(scene) for i in 1:5, j in 1:4 ]
for ax in axes
   ax.titlevisible = false
   ax.xlabelvisible = false
   ax.ylabelvisible = false
   ax.xticklabelsvisible = false
   ax.yticklabelsvisible = false
   ax.xticksvisible = false
   ax.yticksvisible = false
   ax.bottomspinevisible = false
   ax.leftspinevisible = false
   ax.topspinevisible = false
   ax.rightspinevisible = false
end

tightlimits!.(axes)
layout[1:5, 1:4] = axes
display(scene)
for x in 1:100
   imgs = [ rand(28,28) for i in 1:20]
   for (i,ax) in enumerate(axes)
      image!(ax, imgs[i])
   end
   sleep(0.0001)
end
```

A couple of things I notice performance-wise:

1) even after the outerloop is finished I see pretty high CPU useage:

> PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND                                                         
> 28488 phil      20   0 2301848 804876 155368 R  95.4  2.5   7:00.30 julia  

2) Resizing the scene window is very visibly slow. I find this kind of odd given that I've played with lots of interactive Makie 3d plots, for example, which are very responsive. Is this because I have 20 'subplots' (for lack of a better term)? Is there a more efficient way to do this?

**Comment by jkrumbiegel** [comment]
I don't know what very visibly slow means for you, of course, but I assume that the problem is no the number of LAxis but the huge number of separate image plots you're adding to all the axes. Overall, I think you're creating 2000 separate image plots and that will drag your performance down. I'm not the expert in Makie internals but there is probably a more efficient way to do this, by uploading one big texture or using a scatter plot with multiple small textures. Can you try not adding any, or only a few image plots and compare the baseline responsiveness of resizing to what you see? I don't think the layout itself is the problem.

**Comment by jkrumbiegel** [comment]
Oh also you can use hidespines! and hidedecorations! on your axes instead of setting all these attributes manually

**Comment by philtomson** [comment]
Oh, that makes sense (the 2000 images part). How do I instead of adding new images just replace the current image so that there are only 20 images total? I'm trying to visualize changing data so maybe some kind of animation?

**Comment by jkrumbiegel** [comment]
Make 20 Nodes with arrays inside, use those Nodes in the heatmap calls once, and then assign new data to the Nodes, thereby updating the heatmaps.

Something like 
```julia
arrnodes = [Node(rand(28, 28)) for i in 1:20]
for i in 1:20
    heatmap!(axes[i], arrnodes[i])
end

# to update
for i in 1:20
    arrnodes[i] = rand(28, 28)
end
```

**Comment by philtomson** [comment]
Thanks, that's better. Much more performant and I don't see that odd CPU useage after the loop finishes. 
Had to modify your suggested code a bit to get it to work:

```
arrnodes = [Node(rand(28,28)) for i in 1:20]
for i in 1:20
   image!(axes[i], arrnodes[i])
end

display(scene)
for x in 1:100
   for i in 1:20
      (arrnodes[i])[] = rand(28,28)
   end
   sleep(0.0001)
end
```

**Comment by jkrumbiegel** [comment]
glad to hear you got it to work!
