### ISSUE TITLE
How to make slider span all "possible"/allowed width?

### ISSUE THREAD

**Issue by Datseris** [jkrumbiegel/MakieLayout#82]
Here is a MWE
```julia
scene, layout = layoutscene()
display(scene)
abmax = layout[1,1] = LAxis(scene)
scatter!(abmax, rand(5), rand(5))
controllayout = layout[1, 2] = GridLayout(tellheight = false)
firstrow = controllayout[1, :] = GridLayout(tellheight = false, tellwidth=false)
run = LButton(scene, label = "run")
update = LButton(scene, label = "update")
spusl = labelslider!(scene, "spu =", 0:10)
slesl = labelslider!(scene, "sleep =", 0:0.1:10; width = Relative(1))
firstrow[1, :] = spusl.layout
firstrow[2, :] = slesl.layout
reset = LButton(scene, label = "reset")
firstrow[3, :] = hbox!(run, update, reset)
```

That produces:

![image](https://user-images.githubusercontent.com/19669089/84431035-e5aac780-ac2a-11ea-8690-eee920cb4e51.png)

Adding or removing the `width = Relative(1)` has no impact. 

I initially expected the default arguments of `slider!` to make it use all available space. How do I achieve that?

**Comment by jkrumbiegel** [comment]
The sliders are taking all available space, it's just that the GridLayout reports its size to be that of the three buttons. You should be able to fix it like this (didn't test it):

```julia
firstrow[3, :] = hbox!(run, update, reset, tellwidth = false)
```

**Comment by Datseris** [comment]
After searching many possibilities, I now know the solution: it is not the slider's problem, it is the buttons!!!

Adding `, width = Auto(), tellwidth = false` to all buttons fixes the issue!

**Comment by Datseris** [comment]
HA! I _almost_ got it before you

**Comment by jkrumbiegel** [comment]
just with the difference that you can use the attribute on the `hbox` and don't have to use it on each button :) (that would have a different effect)

**Comment by Datseris** [comment]
Yeap, thanks, very useful, I've updated my code!
